### ISSUE TITLE
The class 'ScnSocialAuth\Entity\UserProvider' was not found in the chain configured namespaces

### ISSUE THREAD

**Issue by carvagu** [SocalNick/ScnSocialAuthDoctrineORM#23]
#0 /home/storage/1/55/6c/oreidafesta/public_html/oreidafesta/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(112): Doctrine\Common\Persistence\Mapping\MappingException::classNotFoundInNamespaces('ScnSocialAuth\\E...', Array)
#1 /home/storage/1/55/6c/oreidafesta/public_html/oreidafesta/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(117): Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain->loadMetadataForClass('ScnSocialAuth\\E...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#2 /home/storage/1/55/6c/oreidafesta/public_html/oreidafesta/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(332): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array)
#3 /home/storage/1/55/6c/oreidafesta/public_html/oreidafesta/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(216): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('ScnSocialAuth\\E...')
#4 /home/storage/1/55/6c/oreidafesta/public_html/oreidafesta/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(265): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('ScnSocialAuth\\E...')
#5 /home/storage/1/55/6c/oreidafesta/public_html/oreidafesta/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php(67): Doctrine\ORM\EntityManager->getClassMetadata('ScnSocialAuth\\E...')
#6 /home/storage/1/55/6c/oreidafesta/public_html/oreidafesta/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php(50): Doctrine\ORM\Repository\DefaultRepositoryFactory->createRepository(Object(Doctrine\ORM\EntityManager), 'ScnSocialAuth\\E...')
#7 /home/storage/1/55/6c/oreidafesta/public_html/oreidafesta/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(665): Doctrine\ORM\Repository\DefaultRepositoryFactory->getRepository(Object(Doctrine\ORM\EntityManager), 'ScnSocialAuth\\E...')
#8 /home/storage/1/55/6c/oreidafesta/public_html/oreidafesta/vendor/socalnick/scn-social-auth-doctrine-orm/src/ScnSocialAuthDoctrineORM/Mapper/UserProvider.php(42): Doctrine\ORM\EntityManager->getRepository('ScnSocialAuth\\E...')
#9 /home/storage/1/55/6c/oreidafesta/public_html/oreidafesta/vendor/socalnick/scn-social-auth/src/ScnSocialAuth/Authentication/Adapter/HybridAuth.php(99): ScnSocialAuthDoctrineORM\Mapper\UserProvider->findUserByProviderId('102054836494435...', 'facebook')

any help??

**Comment by SocalNick** [comment]
Seems like it should actually be `ScnSocialAuthDoctrineORM\Entity\UserProvider`, right? Maybe @jhuet / @dorongutman could help?

Maybe sending your `config/application.config.php` could help us debug.
